web/webapp/news/models.py
from webapp.db import db


class News(db.Model):

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String, nullable=False)
    url = db.Column(db.String, unique=True, nullable=False)
    published = db.Column(db.DateTime, nullable=False)
    text = db.Column(db.Text, nullable=True)

    def __repr__(self) -> str:
        return f"<News {self.title} {self.url}>"

web/webapp/user/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash


from webapp.db import db


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    password = db.Column(db.String(128))
    role = db.Column(db.String(10), index=True)
    email = db.Column(db.String(50), unique=True)

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    @property
    def is_admin(self):
        return self.role == 'admin'

    def __repr__(self) -> str:
        return f"<User {self.username}>"

web/webapp/user/forms.py
from email.policy import default
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    username = StringField('Имя пользователя', validators=[DataRequired()], render_kw={"class": "form-control"})
    password = PasswordField('Пароль', validators=[DataRequired()], render_kw={"class": "form-control"})
    remember_me = BooleanField('Запомнить меня', default=True, render_kw={"class": "form-check-imput"})
    submit = SubmitField('Отправить', render_kw={"class": "btn btn-primary"})

web/webapp/__init__.py
from flask import Flask
from flask_login import LoginManager

from flask_migrate import Migrate

from webapp.db import db
from webapp.user.models import User
from webapp.user.views import blueprint as user_blueprint
from webapp.admin.views import blueprint as admin_blueprint
from webapp.news.views import blueprint as news_blueprint


def create_app():
    app = Flask(__name__)
    app.config.from_pyfile('config.py')
    db.init_app(app)
    migrate = Migrate(app, db, render_as_batch=True)

    login_manager = LoginManager()
    login_manager.init_app(app)
    login_manager.login_view = 'user.login'
    app.register_blueprint(admin_blueprint)
    app.register_blueprint(news_blueprint)
    app.register_blueprint(user_blueprint)

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(user_id)

    return app

web/webapp/admin/views.py
from webapp.user.decorators import admin_required
from flask import Blueprint, render_template


blueprint = Blueprint('admin', __name__, url_prefix='/admin')


@blueprint.route('/')
@admin_required
def admin_index():    
    title = 'Панель управления'
    return render_template('admin/index.html', page_title=title)
    

web/webapp/news/views.py
from flask import render_template, Blueprint, current_app
from webapp.weather import weather_by_city
from webapp.news.models import News


blueprint = Blueprint('news', __name__)


@blueprint.route('/')
def index():
    page_title = "Новости Python"
    weather = weather_by_city(current_app.config['WEATHER_DEFAULT_CITY'])
    news_list = News.query.order_by(News.published.desc()).all()
    return render_template('news/index.html', page_title=page_title,
                           weather=weather,
                           news_list=news_list)

web/webapp/user/views.py
from webapp.user.models import User
from webapp.user.forms import LoginForm
from flask import render_template, flash, redirect, url_for, Blueprint
from flask_login import login_user, logout_user, current_user


blueprint = Blueprint('user', __name__, url_prefix='/users')


@blueprint.route('/login')
def login():
    if current_user.is_authenticated:
        return redirect(url_for('news.index'))
    title = 'Авторизация'
    login_form = LoginForm()
    return render_template('login.html', page_title=title, form=login_form)


@blueprint.route('/process-login', methods=['POST'])
def process_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter(User.username == form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash('Вы успешно зашли на сайт')
            return redirect(url_for('news.index'))
    flash('Неправильные имя или пароль')
    return redirect(url_for('user.login'))


@blueprint.route('/logout')
def logout():
    logout_user()
    flash('Вы успешно разлогинились')
    return redirect(url_for('news.index'))

web/webapp/templates/base.html
<!doctype html>
<html lang="ru">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>{{ page_title }}</title>
</head>

<body>
    {% include 'menu.html' %}
    <div class="container">        
        <h1>
            {{ page_title }}
        </h1>

        {% block content %}

        {% endblock %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
</body>

</html>

web/webapp/templates/index.html
<!doctype html>
<html lang="ru">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>{{ page_title }}</title>
</head>

<body>
    <div class="container">
        <h1>
            {{ page_title }}
        </h1>

        <div class="row">
            <div class="col-8">
                <h2>Новости</h2>
                {% if news_list %}
                    {% for news in news_list  %}

                    <h3>
                        <a href="{{ news.url }}">{{ news.title }}</a>
                    </h3>
                    <p>{{ news.published.strftime('%d.%m.%Y') }}</p>
                    <hr>

                    {% endfor %}
                {% else %}
                Сервис новостей не доступен
                {% endif %}
            </div>
            <div class="col-4">
                <h2>Погода</h2>
                {% if weather %}
                Погода: {{ weather.temp_C }}, ощущается как: {{ weather.FeelsLikeC }}
                {% else %}
                Сервис погоды не доступен
                {% endif %}
            </div>
        </div>

    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
</body>

</html>

web/webapp/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-4">

        {% with messages = get_flashed_messages() %}
            {% if messages %}
            <div class="alert alert-warning" role="alert">
                {% for message in messages %}
                    {{ message }} <br>
                {% endfor %}
            </div>
            {% endif %}
        {% endwith %}

        <form action="{{ url_for('user.process_login') }}" method="POST">
            {{ form.hidden_tag() }}

            <div class="form-group">
                {{ form.username.label }}
                {{ form.username() }}
            </div>
                
            <div class="form-group">
                {{ form.password.label }}
                {{ form.password() }}
            </div>
            
            <div class="form-group form-check">                        
                {{ form.remember_me() }} 
                {{ form.remember_me.label(class_='from-check-label') }}
            </div>

            {{ form.submit() }}                    
        </form>
    </div>
    <div class="col-5">
        
    </div>
</div>
{% endblock %}

web/webapp/templates/menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<div class="container-fluid">
    <a class="navbar-brand" href="#">Новости Python</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="/">Главная страница</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="{{ url_for('user.login') }}">Логин</a>
        </li>
    </ul>
    <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Искать</button>
    </form>
    </div>
</div>
</nav>

web/webapp/templates/news/index.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-8">

        {% with messages = get_flashed_messages() %}
            {% if messages %}
            <div class="alert alert-warning" role="alert">
                {% for message in messages %}
                    {{ message }} <br>
                {% endfor %}
            </div>
            {% endif %}
        {% endwith %}

        <h2>Новости</h2>
        {% if news_list %}
            {% for news in news_list  %}

            <h3>
                <a href="{{ news.url }}">{{ news.title }}</a>
            </h3>
            <p>{{ news.published.strftime('%d.%m.%Y') }}</p>
            <hr>

            {% endfor %}
        {% else %}
        Сервис новостей не доступен
        {% endif %}
    </div>
    <div class="col-4">
        <h2>Погода</h2>
        {% if weather %}
        Погода: {{ weather.temp_C }}, ощущается как: {{ weather.FeelsLikeC }}
        {% else %}
        Сервис погоды не доступен
        {% endif %}
    </div>
</div>
{% endblock %}